services:
    database:
        container_name: database
        build: database
        volumes:
            - ./database/data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 3s
            retries: 5
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=postgres

    streamlit-app:
        container_name: streamlit-app
        build: app
        depends_on:
            database:
                condition: service_healthy
        volumes:
            - ./app:/app
            - /tmp/poetry_cache:/tmp/poetry_cache
        ports:
            - '8501:8501'
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
            - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
            - DB_HOST=database
            - DB_PORT=5432
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_NAME=next
        user: appuser
        restart: unless-stopped
        healthcheck:
            test:
                ['CMD', 'curl', '-fsS', 'http://localhost:8501/_stcore/health']
            interval: 30s
            timeout: 5s
            start_period: 30s
            retries: 3
