services:
    streamlit-app:
        container_name: streamlit-app
        build: app
        volumes:
            - ./app:/app
            - /tmp/poetry_cache:/tmp/poetry_cache
        ports:
            - '8501:8501'
        environment:
            - PYTHONDONTWRITEBYTECODE=1
            - PYTHONUNBUFFERED=1
            - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
        user: appuser
        restart: unless-stopped
        healthcheck:
            test:
                ['CMD', 'curl', '-fsS', 'http://localhost:8501/_stcore/health']
            interval: 30s
            timeout: 5s
            start_period: 30s
            retries: 3
        mem_limit: 8g
        mem_reservation: 3g
        shm_size: '1g'
